/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package games.tunnelescape.tunnelescape;

public class Pair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Pair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        WorldWrapperModuleJNI.delete_Pair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Pair() {
    this(WorldWrapperModuleJNI.new_Pair__SWIG_0(), true);
  }

  public Pair(long first, long second) {
    this(WorldWrapperModuleJNI.new_Pair__SWIG_1(first, second), true);
  }

  public long getFirst() {
    return WorldWrapperModuleJNI.Pair_getFirst(swigCPtr, this);
  }

  public long getSecond() {
    return WorldWrapperModuleJNI.Pair_getSecond(swigCPtr, this);
  }

  public void setFirst(long first) {
    WorldWrapperModuleJNI.Pair_setFirst(swigCPtr, this, first);
  }

  public void setSecond(long second) {
    WorldWrapperModuleJNI.Pair_setSecond(swigCPtr, this, second);
  }

}
