/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package games.tunnelescape.tunnelescape;

public class ShapeModuleJNI {
  public final static native long new_Shape__SWIG_0();
  public final static native long new_Shape__SWIG_1(float jarg1, float jarg2);
  public final static native long new_Shape__SWIG_2(long jarg1, Shape jarg1_);
  public final static native long Shape_getPointer(long jarg1, Shape jarg1_);
  public final static native long Shape_getCenter(long jarg1, Shape jarg1_);
  public final static native long Shape_getFrame(long jarg1, Shape jarg1_);
  public final static native Vector2f Shape_getMin(long jarg1, Shape jarg1_);
  public final static native Vector2f Shape_getMax(long jarg1, Shape jarg1_);
  public final static native float Shape_getArea(long jarg1, Shape jarg1_);
  public final static native int Shape_getEdges(long jarg1, Shape jarg1_);
  public final static native long Shape_getAxis(long jarg1, Shape jarg1_);
  public final static native float Shape_getWidth(long jarg1, Shape jarg1_);
  public final static native float Shape_getHeight(long jarg1, Shape jarg1_);
  public final static native void delete_Shape(long jarg1);
  public final static native long new_Vector2f__SWIG_0(float jarg1, float jarg2);
  public final static native long new_Vector2f__SWIG_1();
  public final static native long new_Vector2f__SWIG_2(long jarg1, Vector2f jarg1_);
  public final static native long Vector2f_getPointer(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_getX(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_getY(long jarg1, Vector2f jarg1_);
  public final static native void Vector2f_update(long jarg1, Vector2f jarg1_, float jarg2, float jarg3);
  public final static native void Vector2f_normalize(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_dotProduct(long jarg1, Vector2f jarg1_, long jarg2, Vector2f jarg2_);
  public final static native long Vector2f_rotate(long jarg1, Vector2f jarg1_, float jarg2);
  public final static native float Vector2f_getAngle(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_getLength(long jarg1, Vector2f jarg1_);
  public final static native float dotProduct__SWIG_1(long jarg1, Vector2f jarg1_, long jarg2, Vector2f jarg2_);
  public final static native void delete_Vector2f(long jarg1);
  public final static native boolean Vector2fDeque_empty(long jarg1, Vector2fDeque jarg1_);
  public final static native long new_Vector2fDeque__SWIG_0();
  public final static native long new_Vector2fDeque__SWIG_1(long jarg1, long jarg2, Vector2f jarg2_);
  public final static native long new_Vector2fDeque__SWIG_2(long jarg1);
  public final static native long new_Vector2fDeque__SWIG_3(long jarg1, Vector2fDeque jarg1_);
  public final static native void delete_Vector2fDeque(long jarg1);
  public final static native void Vector2fDeque_assign(long jarg1, Vector2fDeque jarg1_, long jarg2, long jarg3, Vector2f jarg3_);
  public final static native void Vector2fDeque_swap(long jarg1, Vector2fDeque jarg1_, long jarg2, Vector2fDeque jarg2_);
  public final static native long Vector2fDeque_size(long jarg1, Vector2fDeque jarg1_);
  public final static native long Vector2fDeque_max_size(long jarg1, Vector2fDeque jarg1_);
  public final static native void Vector2fDeque_resize__SWIG_0(long jarg1, Vector2fDeque jarg1_, long jarg2, long jarg3, Vector2f jarg3_);
  public final static native void Vector2fDeque_resize__SWIG_1(long jarg1, Vector2fDeque jarg1_, long jarg2);
  public final static native long Vector2fDeque_front(long jarg1, Vector2fDeque jarg1_);
  public final static native long Vector2fDeque_back(long jarg1, Vector2fDeque jarg1_);
  public final static native void Vector2fDeque_push_front(long jarg1, Vector2fDeque jarg1_, long jarg2, Vector2f jarg2_);
  public final static native void Vector2fDeque_push_back(long jarg1, Vector2fDeque jarg1_, long jarg2, Vector2f jarg2_);
  public final static native void Vector2fDeque_pop_front(long jarg1, Vector2fDeque jarg1_);
  public final static native void Vector2fDeque_pop_back(long jarg1, Vector2fDeque jarg1_);
  public final static native void Vector2fDeque_clear(long jarg1, Vector2fDeque jarg1_);
  public final static native long Vector2fDeque_getitem(long jarg1, Vector2fDeque jarg1_, int jarg2);
  public final static native void Vector2fDeque_setitem(long jarg1, Vector2fDeque jarg1_, int jarg2, long jarg3, Vector2f jarg3_);
  public final static native void Vector2fDeque_delitem(long jarg1, Vector2fDeque jarg1_, int jarg2);
  public final static native long Vector2fDeque_getslice(long jarg1, Vector2fDeque jarg1_, int jarg2, int jarg3);
  public final static native void Vector2fDeque_setslice(long jarg1, Vector2fDeque jarg1_, int jarg2, int jarg3, long jarg4, Vector2fDeque jarg4_);
  public final static native void Vector2fDeque_delslice(long jarg1, Vector2fDeque jarg1_, int jarg2, int jarg3);
  public final static native long new_Vector2fVector__SWIG_0();
  public final static native long new_Vector2fVector__SWIG_1(long jarg1);
  public final static native long Vector2fVector_size(long jarg1, Vector2fVector jarg1_);
  public final static native long Vector2fVector_capacity(long jarg1, Vector2fVector jarg1_);
  public final static native void Vector2fVector_reserve(long jarg1, Vector2fVector jarg1_, long jarg2);
  public final static native boolean Vector2fVector_isEmpty(long jarg1, Vector2fVector jarg1_);
  public final static native void Vector2fVector_clear(long jarg1, Vector2fVector jarg1_);
  public final static native void Vector2fVector_add(long jarg1, Vector2fVector jarg1_, long jarg2, Vector2f jarg2_);
  public final static native long Vector2fVector_get(long jarg1, Vector2fVector jarg1_, int jarg2);
  public final static native void Vector2fVector_set(long jarg1, Vector2fVector jarg1_, int jarg2, long jarg3, Vector2f jarg3_);
  public final static native void delete_Vector2fVector(long jarg1);
}
