/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package games.tunnelescape.tunnelescape;

public class ShapeModule {
  public static float dotProduct(Vector2f vect1, Vector2f vect2) {
    return ShapeModuleJNI.dotProduct__SWIG_1(Vector2f.getCPtr(vect1), vect1, Vector2f.getCPtr(vect2), vect2);
  }

}
