/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package games.tunnelescape.tunnelescape;

public class Vector2f {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vector2f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector2f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        WorldWrapperModuleJNI.delete_Vector2f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector2f(float x, float y) {
    this(WorldWrapperModuleJNI.new_Vector2f__SWIG_0(x, y), true);
  }

  public Vector2f() {
    this(WorldWrapperModuleJNI.new_Vector2f__SWIG_1(), true);
  }

  public Vector2f(Vector2f vector2) {
    this(WorldWrapperModuleJNI.new_Vector2f__SWIG_2(Vector2f.getCPtr(vector2), vector2), true);
  }

  public Vector2f getPointer() {
    long cPtr = WorldWrapperModuleJNI.Vector2f_getPointer(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector2f(cPtr, false);
  }

  public float getX() {
    return WorldWrapperModuleJNI.Vector2f_getX(swigCPtr, this);
  }

  public float getY() {
    return WorldWrapperModuleJNI.Vector2f_getY(swigCPtr, this);
  }

  public void update(float x, float y) {
    WorldWrapperModuleJNI.Vector2f_update(swigCPtr, this, x, y);
  }

  public void normalize() {
    WorldWrapperModuleJNI.Vector2f_normalize(swigCPtr, this);
  }

  public float dotProduct(Vector2f vector) {
    return WorldWrapperModuleJNI.Vector2f_dotProduct(swigCPtr, this, Vector2f.getCPtr(vector), vector);
  }

  public Vector2f rotate(float angle) {
    return new Vector2f(WorldWrapperModuleJNI.Vector2f_rotate(swigCPtr, this, angle), false);
  }

  public float getAngle() {
    return WorldWrapperModuleJNI.Vector2f_getAngle(swigCPtr, this);
  }

  public float getLength() {
    return WorldWrapperModuleJNI.Vector2f_getLength(swigCPtr, this);
  }

}
