/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package games.tunnelescape.tunnelescape;

public class Vector2i {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vector2i(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector2i obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        WorldWrapperModuleJNI.delete_Vector2i(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector2i(int x, int y) {
    this(WorldWrapperModuleJNI.new_Vector2i__SWIG_0(x, y), true);
  }

  public Vector2i() {
    this(WorldWrapperModuleJNI.new_Vector2i__SWIG_1(), true);
  }

  public Vector2i(Vector2i vector2) {
    this(WorldWrapperModuleJNI.new_Vector2i__SWIG_2(Vector2i.getCPtr(vector2), vector2), true);
  }

  public Vector2i getPointer() {
    long cPtr = WorldWrapperModuleJNI.Vector2i_getPointer(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector2i(cPtr, false);
  }

  public int getX() {
    return WorldWrapperModuleJNI.Vector2i_getX(swigCPtr, this);
  }

  public int getY() {
    return WorldWrapperModuleJNI.Vector2i_getY(swigCPtr, this);
  }

  public void update(int x, int y) {
    WorldWrapperModuleJNI.Vector2i_update(swigCPtr, this, x, y);
  }

  public void normalize() {
    WorldWrapperModuleJNI.Vector2i_normalize(swigCPtr, this);
  }

  public float dotProduct(Vector2i vector) {
    return WorldWrapperModuleJNI.Vector2i_dotProduct(swigCPtr, this, Vector2i.getCPtr(vector), vector);
  }

  public Vector2i rotate(int angle) {
    return new Vector2i(WorldWrapperModuleJNI.Vector2i_rotate(swigCPtr, this, angle), false);
  }

  public int getAngle() {
    return WorldWrapperModuleJNI.Vector2i_getAngle(swigCPtr, this);
  }

  public int getLength() {
    return WorldWrapperModuleJNI.Vector2i_getLength(swigCPtr, this);
  }

}
