/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package games.tunnelescape.tunnelescape;

public interface WorldWrapperModuleConstants {
  public final static double STD_DENSITY = WorldWrapperModuleJNI.STD_DENSITY_get();
}
