/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.westerholmgmail.v.lauri.tunnelescape;

public class Recti {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Recti(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Recti obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RectJNI.delete_Recti(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Recti() {
    this(RectJNI.new_Recti__SWIG_0(), true);
  }

  public Recti(Vector2i upper_left, int width, int height) {
    this(RectJNI.new_Recti__SWIG_1(Vector2i.getCPtr(upper_left), upper_left, width, height), true);
  }

  public Recti(Recti rect) {
    this(RectJNI.new_Recti__SWIG_2(Recti.getCPtr(rect), rect), true);
  }

  public void setPosition(Vector2i position) {
    RectJNI.Recti_setPosition(swigCPtr, this, Vector2i.getCPtr(position), position);
  }

  public Vector2i getPosition() {
    return new Vector2i(RectJNI.Recti_getPosition(swigCPtr, this), true);
  }

  public void setWidth(int width) {
    RectJNI.Recti_setWidth(swigCPtr, this, width);
  }

  public int getWidth() {
    return RectJNI.Recti_getWidth(swigCPtr, this);
  }

  public void setHeight(int height) {
    RectJNI.Recti_setHeight(swigCPtr, this, height);
  }

  public int getHeight() {
    return RectJNI.Recti_getHeight(swigCPtr, this);
  }

  public void setSize(Vector2i size) {
    RectJNI.Recti_setSize(swigCPtr, this, Vector2i.getCPtr(size), size);
  }

  public Vector2i getSize() {
    return new Vector2i(RectJNI.Recti_getSize(swigCPtr, this), true);
  }

  public boolean contains(int x, int y) {
    return RectJNI.Recti_contains__SWIG_0(swigCPtr, this, x, y);
  }

  public boolean contains(Vector2i point) {
    return RectJNI.Recti_contains__SWIG_1(swigCPtr, this, Vector2i.getCPtr(point), point);
  }

}
