/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.westerholmgmail.v.lauri.tunnelescape;

public class Vector2JNI {
  public final static native long new_Vector2f__SWIG_0(float jarg1, float jarg2);
  public final static native long new_Vector2f__SWIG_1();
  public final static native long new_Vector2f__SWIG_2(long jarg1, Vector2f jarg1_);
  public final static native long Vector2f_getPointer(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_getX(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_getY(long jarg1, Vector2f jarg1_);
  public final static native void Vector2f_update(long jarg1, Vector2f jarg1_, float jarg2, float jarg3);
  public final static native void Vector2f_normalize(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_dotProduct(long jarg1, Vector2f jarg1_, long jarg2, Vector2f jarg2_);
  public final static native long Vector2f_rotate(long jarg1, Vector2f jarg1_, float jarg2);
  public final static native float Vector2f_getAngle(long jarg1, Vector2f jarg1_);
  public final static native float Vector2f_getLength(long jarg1, Vector2f jarg1_);
  public final static native float dotProduct__SWIG_1(long jarg1, Vector2f jarg1_, long jarg2, Vector2f jarg2_);
  public final static native void delete_Vector2f(long jarg1);
  public final static native long new_Vector2i__SWIG_0(int jarg1, int jarg2);
  public final static native long new_Vector2i__SWIG_1();
  public final static native long new_Vector2i__SWIG_2(long jarg1, Vector2i jarg1_);
  public final static native long Vector2i_getPointer(long jarg1, Vector2i jarg1_);
  public final static native int Vector2i_getX(long jarg1, Vector2i jarg1_);
  public final static native int Vector2i_getY(long jarg1, Vector2i jarg1_);
  public final static native void Vector2i_update(long jarg1, Vector2i jarg1_, int jarg2, int jarg3);
  public final static native void Vector2i_normalize(long jarg1, Vector2i jarg1_);
  public final static native float Vector2i_dotProduct(long jarg1, Vector2i jarg1_, long jarg2, Vector2i jarg2_);
  public final static native long Vector2i_rotate(long jarg1, Vector2i jarg1_, int jarg2);
  public final static native int Vector2i_getAngle(long jarg1, Vector2i jarg1_);
  public final static native int Vector2i_getLength(long jarg1, Vector2i jarg1_);
  public final static native int dotProduct__SWIG_2(long jarg1, Vector2i jarg1_, long jarg2, Vector2i jarg2_);
  public final static native void delete_Vector2i(long jarg1);
}
