######################################################################
# Automatically generated by qmake (3.0) Wed May 8 20:33:05 2019
######################################################################

TEMPLATE = app
TARGET = LevelEditor
INCLUDEPATH += .

# Input
HEADERS += include/AssetManager.hpp include/Editor.hpp include/EditorWindow.hpp
SOURCES += src/AssetManager.cpp src/Editor.cpp src/EditorWindow.cpp src/main.cpp
QT += widgets
