######################################################################
# Automatically generated by qmake (3.0) Tue May 7 23:40:00 2019
######################################################################

TEMPLATE = app
TARGET = LevelEditor
INCLUDEPATH += .

# Input
HEADERS += include/Editor.hpp include/EditorWindow.hpp
SOURCES += src/Editor.cpp src/EditorWindow.cpp src/main.cpp

QT += widgets
