/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "WorldWrapper.hpp"


#include <stdexcept>


#include <vector>
#include <stdexcept>


#include <deque>
#include <stdexcept>


#include <map>
#include <algorithm>
#include <stdexcept>

SWIGINTERN std::deque< Pair >::const_reference std_deque_Sl_Pair_Sg__getitem(std::deque< Pair > *self,int i){
                int size = int(self->size());
                if (i<0) i += size;
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("deque index out of range");
           }
SWIGINTERN void std_deque_Sl_Pair_Sg__setitem(std::deque< Pair > *self,int i,Pair const &x){
                int size = int(self->size());
                if (i<0) i+= size;
                if (i>=0 && i<size)
                    (*self)[i] = x;
                else
                    throw std::out_of_range("deque index out of range");
           }
SWIGINTERN void std_deque_Sl_Pair_Sg__delitem(std::deque< Pair > *self,int i){
                int size = int(self->size());
                if (i<0) i+= size;
                if (i>=0 && i<size) {
                    self->erase(self->begin()+i);
                } else {
                    throw std::out_of_range("deque index out of range");
                }
           }
SWIGINTERN std::deque< Pair > std_deque_Sl_Pair_Sg__getslice(std::deque< Pair > *self,int i,int j){
                int size = int(self->size());
                if (i<0) i = size+i;
                if (j<0) j = size+j;
                if (i<0) i = 0;
                if (j>size) j = size;
                std::deque< Pair > tmp(j-i);
                std::copy(self->begin()+i,self->begin()+j,tmp.begin());
                return tmp;
            }
SWIGINTERN void std_deque_Sl_Pair_Sg__setslice(std::deque< Pair > *self,int i,int j,std::deque< Pair > const &v){
                int size = int(self->size());
                if (i<0) i = size+i;
                if (j<0) j = size+j;
                if (i<0) i = 0;
                if (j>size) j = size;
                if (int(v.size()) == j-i) {
                    std::copy(v.begin(),v.end(),self->begin()+i);
                } else {
                    self->erase(self->begin()+i,self->begin()+j);
                    if (i+1 <= size)
                        self->insert(self->begin()+i+1,v.begin(),v.end());
                    else
                        self->insert(self->end(),v.begin(),v.end());
                }
            }
SWIGINTERN void std_deque_Sl_Pair_Sg__delslice(std::deque< Pair > *self,int i,int j){
                int size = int(self->size());
                if (i<0) i = size+i;
                if (j<0) j = size+j;
                if (i<0) i = 0;
                if (j>size) j = size;
                self->erase(self->begin()+i,self->begin()+j);
            }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jdouble JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_STD_1DENSITY_1get(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)(1.);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_ObjectStatus_1exists_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  ObjectStatus *arg1 = (ObjectStatus *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ObjectStatus **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->exists = arg2;
}


SWIGEXPORT jboolean JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_ObjectStatus_1exists_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  ObjectStatus *arg1 = (ObjectStatus *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ObjectStatus **)&jarg1; 
  result = (bool) ((arg1)->exists);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_ObjectStatus_1position_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  ObjectStatus *arg1 = (ObjectStatus *) 0 ;
  Vector2f *arg2 = (Vector2f *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ObjectStatus **)&jarg1; 
  arg2 = *(Vector2f **)&jarg2; 
  if (arg1) (arg1)->position = *arg2;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_ObjectStatus_1position_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  ObjectStatus *arg1 = (ObjectStatus *) 0 ;
  Vector2f *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ObjectStatus **)&jarg1; 
  result = (Vector2f *)& ((arg1)->position);
  *(Vector2f **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1ObjectStatus(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ObjectStatus *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ObjectStatus *)new ObjectStatus();
  *(ObjectStatus **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_delete_1ObjectStatus(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ObjectStatus *arg1 = (ObjectStatus *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ObjectStatus **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Pair_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Pair *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Pair *)new Pair();
  *(Pair **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Pair_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  unsigned int arg2 ;
  Pair *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (Pair *)new Pair(arg1,arg2);
  *(Pair **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Pair_1getFirst(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Pair *arg1 = (Pair *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Pair **)&jarg1; 
  result = (unsigned int)((Pair const *)arg1)->getFirst();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Pair_1getSecond(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Pair *arg1 = (Pair *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Pair **)&jarg1; 
  result = (unsigned int)((Pair const *)arg1)->getSecond();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Pair_1setFirst(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Pair *arg1 = (Pair *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Pair **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  (arg1)->setFirst(arg2);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Pair_1setSecond(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Pair *arg1 = (Pair *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Pair **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  (arg1)->setSecond(arg2);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_delete_1Pair(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Pair *arg1 = (Pair *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Pair **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setPhysicsWorldUpdateInterval(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
  float arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  WorldWrapper::setPhysicsWorldUpdateInterval(arg1);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setPhysicsEngineThreads(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  unsigned int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  WorldWrapper::setPhysicsEngineThreads(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1WorldWrapper(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  WorldWrapper *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (WorldWrapper *)new WorldWrapper();
  *(WorldWrapper **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_delete_1WorldWrapper(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(WorldWrapper **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  std::deque< Pair > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(WorldWrapper **)&jarg1; 
  result = (arg1)->update();
  *(std::deque< Pair > **)&jresult = new std::deque< Pair >((const std::deque< Pair > &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1addObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2, jlong jarg3, jobject jarg3_, jfloat jarg4, jfloat jarg5) {
  jlong jresult = 0 ;
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  bool arg2 ;
  Vector2f arg3 ;
  float arg4 ;
  float arg5 ;
  Vector2f *argp3 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  argp3 = *(Vector2f **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Vector2f");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  result = (unsigned int)(arg1)->addObject(arg2,arg3,arg4,arg5);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1removeObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  (arg1)->removeObject(arg2);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setObjectPhysicsProperties(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jfloat jarg3, jfloat jarg4) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  float arg3 ;
  float arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  (arg1)->setObjectPhysicsProperties(arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setObjectCollisionMask(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  (arg1)->setObjectCollisionMask(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setObjectOriginTransform(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  Vector2f arg3 ;
  Vector2f *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  argp3 = *(Vector2f **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Vector2f");
    return ;
  }
  arg3 = *argp3; 
  (arg1)->setObjectOriginTransform(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setObjectForce(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  Vector2f arg3 ;
  Vector2f *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  argp3 = *(Vector2f **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Vector2f");
    return ;
  }
  arg3 = *argp3; 
  (arg1)->setObjectForce(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setObjectVelocity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  Vector2f arg3 ;
  Vector2f *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  argp3 = *(Vector2f **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Vector2f");
    return ;
  }
  arg3 = *argp3; 
  (arg1)->setObjectVelocity(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1setObjectPosition(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  Vector2f arg3 ;
  Vector2f *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  argp3 = *(Vector2f **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Vector2f");
    return ;
  }
  arg3 = *argp3; 
  (arg1)->setObjectPosition(arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_WorldWrapper_1fetchPosition(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  WorldWrapper *arg1 = (WorldWrapper *) 0 ;
  unsigned int arg2 ;
  ObjectStatus result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(WorldWrapper **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = ((WorldWrapper const *)arg1)->fetchPosition(arg2);
  *(ObjectStatus **)&jresult = new ObjectStatus((const ObjectStatus &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Vector2f_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2) {
  jlong jresult = 0 ;
  float arg1 ;
  float arg2 ;
  Vector2< float > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  result = (Vector2< float > *)new Vector2< float >(arg1,arg2);
  *(Vector2< float > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Vector2f_1_1SWIG_11(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Vector2< float > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Vector2< float > *)new Vector2< float >();
  *(Vector2< float > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Vector2f_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Vector2< float > *arg1 = 0 ;
  Vector2< float > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< float > const & reference is null");
    return 0;
  } 
  result = (Vector2< float > *)new Vector2< float >((Vector2< float > const &)*arg1);
  *(Vector2< float > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1getPointer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  Vector2< float > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  result = (Vector2< float > *)(arg1)->getPointer();
  *(Vector2< float > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1getX(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  result = (float)((Vector2< float > const *)arg1)->getX();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1getY(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  result = (float)((Vector2< float > const *)arg1)->getY();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2, jfloat jarg3) {
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  float arg2 ;
  float arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  (arg1)->update(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1normalize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  (arg1)->normalize();
}


SWIGEXPORT jfloat JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1dotProduct(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jfloat jresult = 0 ;
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  Vector2< float > *arg2 = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Vector2< float > **)&jarg1; 
  arg2 = *(Vector2< float > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< float > const & reference is null");
    return 0;
  } 
  result = (float)((Vector2< float > const *)arg1)->dotProduct((Vector2< float > const &)*arg2);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1rotate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  jlong jresult = 0 ;
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  float arg2 ;
  Vector2< float > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  arg2 = (float)jarg2; 
  result = (Vector2< float > *) &(arg1)->rotate(arg2);
  *(Vector2< float > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1getAngle(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  result = (float)((Vector2< float > const *)arg1)->getAngle();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2f_1getLength(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< float > **)&jarg1; 
  result = (float)((Vector2< float > const *)arg1)->getLength();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_dotProduct_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jfloat jresult = 0 ;
  Vector2< float > *arg1 = 0 ;
  Vector2< float > *arg2 = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Vector2< float > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< float > const & reference is null");
    return 0;
  } 
  arg2 = *(Vector2< float > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< float > const & reference is null");
    return 0;
  } 
  result = (float)dotProduct((Vector2< float > const &)*arg1,(Vector2< float > const &)*arg2);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_delete_1Vector2f(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Vector2< float > *arg1 = (Vector2< float > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Vector2< float > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Vector2i_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  Vector2< int > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (Vector2< int > *)new Vector2< int >(arg1,arg2);
  *(Vector2< int > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Vector2i_1_1SWIG_11(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Vector2< int > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Vector2< int > *)new Vector2< int >();
  *(Vector2< int > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1Vector2i_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Vector2< int > *arg1 = 0 ;
  Vector2< int > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< int > const & reference is null");
    return 0;
  } 
  result = (Vector2< int > *)new Vector2< int >((Vector2< int > const &)*arg1);
  *(Vector2< int > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1getPointer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  Vector2< int > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  result = (Vector2< int > *)(arg1)->getPointer();
  *(Vector2< int > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1getX(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  result = (int)((Vector2< int > const *)arg1)->getX();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1getY(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  result = (int)((Vector2< int > const *)arg1)->getY();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->update(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1normalize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  (arg1)->normalize();
}


SWIGEXPORT jfloat JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1dotProduct(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jfloat jresult = 0 ;
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  Vector2< int > *arg2 = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Vector2< int > **)&jarg1; 
  arg2 = *(Vector2< int > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< int > const & reference is null");
    return 0;
  } 
  result = (float)((Vector2< int > const *)arg1)->dotProduct((Vector2< int > const &)*arg2);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1rotate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  int arg2 ;
  Vector2< int > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Vector2< int > *) &(arg1)->rotate(arg2);
  *(Vector2< int > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1getAngle(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  result = (int)((Vector2< int > const *)arg1)->getAngle();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_Vector2i_1getLength(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Vector2< int > **)&jarg1; 
  result = (int)((Vector2< int > const *)arg1)->getLength();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_dotProduct_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  Vector2< int > *arg1 = 0 ;
  Vector2< int > *arg2 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Vector2< int > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< int > const & reference is null");
    return 0;
  } 
  arg2 = *(Vector2< int > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Vector2< int > const & reference is null");
    return 0;
  } 
  result = (int)dotProduct((Vector2< int > const &)*arg1,(Vector2< int > const &)*arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_delete_1Vector2i(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Vector2< int > *arg1 = (Vector2< int > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Vector2< int > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jboolean JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1empty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  result = (bool)((std::deque< Pair > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1PairDeque_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::deque< Pair > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::deque< Pair > *)new std::deque< Pair >();
  *(std::deque< Pair > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1PairDeque_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  Pair *arg2 = 0 ;
  std::deque< Pair > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (unsigned int)jarg1; 
  arg2 = *(Pair **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Pair const & reference is null");
    return 0;
  } 
  result = (std::deque< Pair > *)new std::deque< Pair >(arg1,(Pair const &)*arg2);
  *(std::deque< Pair > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1PairDeque_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  std::deque< Pair > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  result = (std::deque< Pair > *)new std::deque< Pair >(arg1);
  *(std::deque< Pair > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_new_1PairDeque_1_1SWIG_13(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::deque< Pair > *arg1 = 0 ;
  std::deque< Pair > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::deque< Pair > const & reference is null");
    return 0;
  } 
  result = (std::deque< Pair > *)new std::deque< Pair >((std::deque< Pair > const &)*arg1);
  *(std::deque< Pair > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_delete_1PairDeque(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  unsigned int arg2 ;
  Pair *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = *(Pair **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Pair const & reference is null");
    return ;
  } 
  (arg1)->assign(arg2,(Pair const &)*arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1swap(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  std::deque< Pair > *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = *(std::deque< Pair > **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::deque< Pair > & reference is null");
    return ;
  } 
  (arg1)->swap(*arg2);
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  result = (unsigned int)((std::deque< Pair > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1max_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  result = (unsigned int)((std::deque< Pair > const *)arg1)->max_size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1resize_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  unsigned int arg2 ;
  Pair arg3 ;
  Pair *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  argp3 = *(Pair **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Pair");
    return ;
  }
  arg3 = *argp3; 
  (arg1)->resize(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1resize_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  (arg1)->resize(arg2);
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1front(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  std::deque< Pair >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  result = (std::deque< Pair >::value_type *) &(arg1)->front();
  *(std::deque< Pair >::value_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1back(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  std::deque< Pair >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  result = (std::deque< Pair >::value_type *) &(arg1)->back();
  *(std::deque< Pair >::value_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1push_1front(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  Pair *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = *(Pair **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Pair const & reference is null");
    return ;
  } 
  (arg1)->push_front((Pair const &)*arg2);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1push_1back(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  Pair *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = *(Pair **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Pair const & reference is null");
    return ;
  } 
  (arg1)->push_back((Pair const &)*arg2);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1pop_1front(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  (arg1)->pop_front();
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1pop_1back(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  (arg1)->pop_back();
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  int arg2 ;
  std::deque< Pair >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::deque< Pair >::value_type *) &std_deque_Sl_Pair_Sg__getitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::deque< Pair >::value_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  int arg2 ;
  Pair *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Pair **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Pair const & reference is null");
    return ;
  } 
  try {
    std_deque_Sl_Pair_Sg__setitem(arg1,arg2,(Pair const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1delitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_deque_Sl_Pair_Sg__delitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT jlong JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1getslice(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  jlong jresult = 0 ;
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::deque< Pair > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = std_deque_Sl_Pair_Sg__getslice(arg1,arg2,arg3);
  *(std::deque< Pair > **)&jresult = new std::deque< Pair >((const std::deque< Pair > &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1setslice(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::deque< Pair > *arg4 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg4_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(std::deque< Pair > **)&jarg4;
  if (!arg4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::deque< Pair > const & reference is null");
    return ;
  } 
  std_deque_Sl_Pair_Sg__setslice(arg1,arg2,arg3,(std::deque< Pair > const &)*arg4);
}


SWIGEXPORT void JNICALL Java_com_westerholmgmail_v_lauri_tunnelescape_WorldWrapperModuleJNI_PairDeque_1delslice(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  std::deque< Pair > *arg1 = (std::deque< Pair > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::deque< Pair > **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  std_deque_Sl_Pair_Sg__delslice(arg1,arg2,arg3);
}


#ifdef __cplusplus
}
#endif

